version: '3.8'

services:
  app:
    build:
      context: .
    command: ["sh", "-c", "npx prisma migrate dev && node dist/server.js"]
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@backend-db-1:5432/mydatabase
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
