version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@backend-db-1:5432/mydatabase
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
